name: I Have Spoken

on:
  schedule:
    - cron: '0 8,20 * * *'
  workflow_dispatch:

jobs:
  i-have-spoken:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v4
        with:
          python-version: "3.8"
          cache: "pip"

      - run: pip3 install -r src/requirements.txt
        shell: bash

      - run: python3 src/main.py  
        env:
          OPENAI_API_KEY: ${{secrets.OPENAI_API_KEY}}
          CONSUMER_KEY: ${{secrets.CONSUMER_KEY}}
          CONSUMER_SECRET: ${{secrets.CONSUMER_SECRET}}
          ACCESS_TOKEN: ${{secrets.ACCESS_TOKEN}}
          ACCESS_TOKEN_SECRET: ${{secrets.ACCESS_TOKEN_SECRET}}
        shell: bash

      - uses: EndBug/add-and-commit@v9
        with:
          default_author: github_actions
